### ISSUE TITLE
[BUG] - Dualboot issue with DualbootKernelPatcher

### ISSUE THREAD

**Issue by Wycboos1** [erdilS/Port-Windows-11-Xiaomi-Pad-5#354]
### Description

I followed the tutorial in the [link](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/dbkp-en.md)
to patch boot.img (**Magnetic Case** method). When I flashed the file and tried to boot Windows using this method (Close the magnetic case), the Aloha logo was successfully displayed on the screen, but it **could not** boot into Windows (no Windows spinning animation), then it went black and automatically restarted. **(Stuck in boot loop)** I tried again, but the problem remained. Later, Windows displayed the message **"Preparing Automatic Repair"** and then **got stuck**. But if I flash the [nabu_uefi_v4.img](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/releases/download/UEFI/nabu-uefi-v4.img) file into the boot partition, or boot directly with the nabu_uefi_v4.img file, I can boot into Windows normally. What is the reason?

I want to flash once with the dualboot patched boot.img to avoid potential risks caused by frequent flashing of the boot partition with nabu_uefi_v4.img or original boot file. What should I do now?

### Reproduction steps

```bash
Follow the tutorial in the link https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/dbkp-en.md to patch the original boot.img file (magnetic case method). Then flash the dualboot patched boot file and restart the pad with the magnetic case closed. And then it will go black and restart automatically.(Stuck in boot loop)
```

### Logs

```bash

```

### Agreement

- [x] I am using the latest Drivers and UEFI.
- [x] I am running Windows 11 on the tablet.
- [x] There is no issue already describing my problem.

**Comment by n00b69** [comment]
@Wycboos1 Did you patch it manually or with woa helper?

**Comment by Wycboos1** [comment]
@n00b69 I patched it manually with magiskboot and DualbootKernelPatcher. And the latest version of woa helper doesn't work on HyperOS.

**Comment by Wycboos1** [comment]
@n00b69 

https://github.com/user-attachments/assets/894091fd-2652-49b6-91d7-0c8bb25855a4

After opening the app, it gets stuck on a white screen.

**Comment by n00b69** [comment]
Ok that should be fixed in a day or two.

Redownload nabu.fd and try repatching. It should work now.

**Comment by n00b69** [comment]
@n00b69 Please download this apk + logfox, filter logging for "woahelper" and send the logs

https://t.me/woahelperchat/302750

**Comment by Wycboos1** [comment]
@n00b69 Here is the crash log of woahelper.
[woahelper_crash.log](https://github.com/user-attachments/files/21114530/woahelper_crash.log)

The following log was filtered from Logfox and contains entries related to "woahelper".
[08_07_woahelper.log](https://github.com/user-attachments/files/21114539/08_07_woahelper.log)

**Comment by Wycboos1** [comment]
> [@Wycboos1](https://github.com/Wycboos1) I have just tested myself by patching boot image on windows and everything working fine with dbkp magnetic case one, also I did flash your patched boot (new-boot.img) that also working fine
> 
> maybe its related to BCD on your side, try doing this and then test again
> 
> 1. Boot [modded twrp](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/releases/download/1.0/recovery.img) from fastboot
> 2. Run these commands to format ESP partition, enable MSC and re-create BCD boot files
> 
> `adb shell format esp`
> 
> `adb shell msc`
> 
> 3. assign letters to ESPNABU and WINNABU drive
> 
> `bcdboot X:\Windows /s Y: /f UEFI`
> 
> Note: if WINNABU and ESPNABU Mounted Drive letters is different - replace X: with actual assigned letter to WINNABU replace Y: with actual assigned letter to ESPNABU

I flashed the new‑boot.img patched with the latest nabu.fd and recreated the ESP partition files following the method, but the issue still persists. How should I go about debugging the boot error?

**Comment by ArKT-7** [comment]
@Wycboos1, i think i found the issue and probably fixed as well, i wonder if you can test with this boot.img as you on hyperos/miui14, 

After extracting/unzip the file just flash this boot.img file in fastboot
or you can use WOA helper to flash, by copying the boot.img to UEFI folder, but make sure to delete all .img file present in that UEFI folder, then in woa helper use "quickboot to windows" to flash in boot partition and reboot

test with your magnetic case, let me know if it works, then will update repo with fix!

You can download from:

- [Download through Google drive](https://drive.google.com/file/d/1-n7nPYg9P5uj4v2eM8FiEeM7kLnbcE7a/view?usp=sharing)
- [Download through One Drive](https://1drv.ms/u/c/e503a90e3c75d1ba/EZgn6AwxZpBGgBvzWxxfhG8BehuKfPK94GA_SHb9CuylNg)
